# Generated by Django 3.1.3 on 2020-11-29 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=300)),
                ('action', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
