# Generated by Django 3.1.3 on 2020-12-20 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_auto_20201129_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cookie', models.CharField(max_length=1000)),
                ('occupation', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
