# Generated by Django 3.1.3 on 2021-01-03 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0005_useraction_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='time',
            field=models.DateTimeField(null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraction',
            name='timestep',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='simulations.simulationplayer'),
        ),
    ]
