# Generated by Django 3.1.3 on 2021-01-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0006_auto_20210103_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
