# Generated by Django 3.0.3 on 2021-03-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0007_auto_20210103_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
